# Generated by Django 3.0.14 on 2021-10-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alc', models.FloatField(default=5)),
                ('ibu', models.FloatField(default=10)),
                ('type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('brewery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Brewery')),
            ],
        ),
    ]
